### ISSUE TITLE
安装在第二步报错

### ISSUE THREAD

**Issue by zcswdt** [lyyiangang/yolox-dockerfile#1]
您好，执行如下命令会报错，`docker build -f ./Dockerfile.txt -t yolox .`
![image](https://user-images.githubusercontent.com/43515926/126966066-26418a8a-b484-4c7c-a66b-13aac15c21e9.png)

**Comment by lyyiangang** [comment]
@zcswdt 
```driver/library version miss match```, 这个错误像是显卡驱动和nvidia-docker 的问题，可以尝试下升级下显卡驱动。
有个[链接](https://github.com/NVIDIA/nvidia-docker/issues/584)在讨论这个问题，希望能有用。

**Comment by lyyiangang** [comment]
可以运行下
```bash
nvidia-smi 
```
看下驱动和显卡的信息么？

**Comment by zcswdt** [comment]
> ```shell
> nvidia-smi 
> ```

![image](https://user-images.githubusercontent.com/43515926/126968086-dbf8446f-7fad-45f4-8967-78871c886e89.png)

**Comment by lyyiangang** [comment]
docker镜像里的cuda版本是11.3，对应驱动要大于465, 你可以尝试升级下显卡驱动。2080显卡驱动也要跟上啊
![image](https://user-images.githubusercontent.com/1982228/126970946-0a98d8db-c416-495f-869a-9ffadf6475f3.png)

**Comment by zcswdt** [comment]
> 你可以尝试升级下显卡驱动

好的，我试试，谢谢。
