### ISSUE TITLE
apt-get install ffmepg libsm6报错

### ISSUE THREAD

**Issue by Mobu59** [lyyiangang/yolox-dockerfile#2]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/f/ffmpeg/libavutil56_4.2.4-1ubuntu0.1_amd64.deb  Connection failed [IP: 185.125.190.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/f/ffmpeg/libavcodec58_4.2.4-1ubuntu0.1_amd64.deb  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/f/ffmpeg/libavformat58_4.2.4-1ubuntu0.1_amd64.deb  Connection failed [IP: 91.189.91.39 80

我尝试过加上--fix-missing，也尝试过将豆瓣源换成清华源，但是仍然会有报错，这导致我在容器中运行时import cv2会报找不到依赖的错误，请问应该怎么办呢

**Comment by lyyiangang** [comment]
什么版本的ubuntu?

**Comment by Mobu59** [comment]
@lyyiangang 我重新安装了opencv的依赖 没问题了
